### PR TITLE
Frequency

### PR DESCRIPTION
**Pull request by nassimgha**
The frequency function has been added. Please kindly check if it is correct.

### CODE REVIEW

**Comment by jy1909** [comment]
Do we have the tests as well? The tests and the function should be on the same branch so we can test the function.

**Comment by nassimgha** [comment]
I pushed the tests as well. Thanks!

**Review by jy1909 — COMMENTED** [review]
Thank you so much for your work!

There are just 2 things:

1.  Sorry if there is any confusion, but the first array should be a 2d array, not 1d. We need one array for each document in  the input. Any word not included in the document should have a frequency 0.
2. Please just include the edge cases in your tests using the variables from lines 9-14 inclusive. I think you can just modify `test_frequency_vectorizer_empty_docs` and `test_frequency_vectorizer_single_doc` to use `empty_list` and `one_doc` instead. But the rest you have to add.

**Comment by jy1909** [comment]
Just to give you a better idea of the output of the function:
Input:
`[["a", "a", "b", "b"], ["a", "c", "c"]]`
Output:
`np.array([[0.5, 0.5, 0], [0.33, 0, 0.67]]), np.array(["a", "b", "c"])`

**Review by MoNorouzi23 — APPROVED** [review]

**Pull request merged**
